### ISSUE TITLE
Missing `train_det_res_sep.json` file for training 

### ISSUE THREAD

**Issue by vidhiJain** [594zyc/HiTUT#1]
I am trying to train mmt with this command:
```
python models/train/train_mmt.py --gpu --use_bert --bert_model roberta --dropout 0.1 --drop_input 0.1 --enable_feat_posture --train_level mix --train_proportion 100 --valid_metric type --batch 84 --lr 5e-5 --focal_loss --emb_init xavier --emb_dim 768  --bert_lr_schedule --early_stop 2 --seed 999 --low_data all --exp_temp YOUR_EXP_PATH_NAME  --name_temp YOUR_EXP_NAME
```
It reports back the following error regarding file not found. It seems that `train_det_res_sep.json` file is missing from the download file for full_2.1.0_pp. 
```
FileNotFoundError: [Errno 2] No such file or directory: 'data/full_2.1.0_pp/train_det_res_sep.json'
```

**Comment by 594zyc** [comment]
Hi Vidhi, 

Thanks for trying out the code. 

I just checked `full_2.1.0_pp.tar.gz`  and found that the file you mentioned has been included. Did you extract everything from the archive file? Maybe something goes wrong with the unzipping process. Could you please retry it? I also sent you an email of the file in case it is the only file you missed. Hope it will work.

**Comment by vidhiJain** [comment]
Thank you! It works!
