### ISSUE TITLE
About Data Preprocessing

### ISSUE THREAD

**Issue by yizhouzhao** [594zyc/HiTUT#2]
Thanks for sharing this great work. I am wondering how did you process the data into **full_2.1.0_pp**. There are so many files in this folder. Could you tell me how to get them.

**Comment by 594zyc** [comment]
Hi Yizhou,

Thanks for trying out the code. Please check the `dataset.py` for how data preprocessing works. It is under the data folder.

**Comment by yizhouzhao** [comment]
Thank you so much for this awesome work and your quick replay!

**Comment by yizhouzhao** [comment]
One more question, I notice that dataset.py needs the model called **_maskrcnn_all.pth_** to perform data processing. Could you please point out where I can find it?

**Comment by 594zyc** [comment]
Hi Yizhou,

I pretrained two Mask RCNN detectors, one detects all objects and receptacles simultaneously, and the other includes two MRCNNs that detect objects and receptacles separately. As I found that the separated version yields better results, the following experiments are based on that and I only release the separated pretrained detector. 

To run the preprocessing code, please try removing the "all" option in line 261 and 666 in `dataset.py`.

**Comment by yizhouzhao** [comment]
Thanks again!
