### ISSUE TITLE
Hardware specifications and wall-clock time to reproduce training

### ISSUE THREAD

**Issue by unnat** [594zyc/HiTUT#4]
Hi @594zyc,

Thanks for the releasing very clean code! 

The on a T4 GPU (high CPU cheap VM 😄), I run out of memory with default `--num_threads 0` and `--batch 84`. I lowered the `--batch 72` to make it fit. 

Was wondering what GPU/CPU infrastructures did you try and worked best for you. 

Also, how long does it take to train (on the above infrastructure) with the defaults mentioned in [Training](https://github.com/594zyc/HiTUT/blob/main/README.md#training)

**Comment by 594zyc** [comment]
Hi @unnat,

Thanks for your interest in our work. I used a Tesla V100 GPU with 20 CPU cores to train the model. Training should be done in 1 day using the default setting. 

Best,
Yichi

**Comment by unnat** [comment]
Thanks for the quick response.
So the default of `--epochs 50` on V100 + 20 CPUs takes wall clock time <= 1 day. T4 is significantly slower with 2 epochs in 12 hours. 

Followup question: My training simply uses a single CPU*. I was wondering when you said 20 CPUs, did you use a different training command from what you mentioned [here](https://github.com/594zyc/HiTUT/blob/main/README.md#training). Otherwise, how do you suggest we use more than one core? 

\* probably because the default for `--num_threads` is `0` ([here](https://github.com/594zyc/HiTUT/blob/7c10663e2056e6dc4dcdc943e8f70602c71089d4/models/config/configs.py#L86))

**Comment by unnat** [comment]
Hi @594zyc,
Gently checking in on the above request.

**Comment by 594zyc** [comment]
Hi @unnat ,

Sorry for the late response. In my experiments the training early stops in around 10 epochs, thus not gonna lasts for 50 epochs.  

For your follow-up question, a single CPU should be fine for training. But for inference you may need more CPUs because the AI2THOR environment is very CPU intensive. Sorry for the confusion made earlier. `num_threads` is only useful during inference.

**Comment by unnat** [comment]
This clears my understanding. Thanks again, @594zyc!
