### ISSUE TITLE
Unable to download trained model

### ISSUE THREAD

**Issue by kc099** [594zyc/HiTUT#5]
Hi, the trained model download link (gdown https://drive.google.com/uc?id=1ykVUiXOrFTqHIdaOsyYEKeqZQzMngPR0 -O exp/Jan27-roberta-mix.zip) doesn't seem to be working now.

Is there any other alternate link to get the trained model?

Thanks.

**Comment by 594zyc** [comment]
Hi @kc099, the link works from my side. What error message do you get?

**Comment by kc099** [comment]
Thanks. It works now.

I got this error before:
"_Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6ddd946b10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))_"
